// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: main.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace BCCMedia.BibleServer {
  public static partial class BibleServer
  {
    static readonly string __ServiceName = "bibleserver.BibleServer";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::BCCMedia.BibleServer.GetVersesRequest> __Marshaller_bibleserver_GetVersesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::BCCMedia.BibleServer.GetVersesRequest.Parser));
    static readonly grpc::Marshaller<global::BCCMedia.BibleServer.GetVersesResponse> __Marshaller_bibleserver_GetVersesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::BCCMedia.BibleServer.GetVersesResponse.Parser));

    static readonly grpc::Method<global::BCCMedia.BibleServer.GetVersesRequest, global::BCCMedia.BibleServer.GetVersesResponse> __Method_GetVerses = new grpc::Method<global::BCCMedia.BibleServer.GetVersesRequest, global::BCCMedia.BibleServer.GetVersesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetVerses",
        __Marshaller_bibleserver_GetVersesRequest,
        __Marshaller_bibleserver_GetVersesResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::BCCMedia.BibleServer.MainReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of BibleServer</summary>
    [grpc::BindServiceMethod(typeof(BibleServer), "BindService")]
    public abstract partial class BibleServerBase
    {
      public virtual global::System.Threading.Tasks.Task<global::BCCMedia.BibleServer.GetVersesResponse> GetVerses(global::BCCMedia.BibleServer.GetVersesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for BibleServer</summary>
    public partial class BibleServerClient : grpc::ClientBase<BibleServerClient>
    {
      /// <summary>Creates a new client for BibleServer</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public BibleServerClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for BibleServer that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public BibleServerClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected BibleServerClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected BibleServerClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::BCCMedia.BibleServer.GetVersesResponse GetVerses(global::BCCMedia.BibleServer.GetVersesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetVerses(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::BCCMedia.BibleServer.GetVersesResponse GetVerses(global::BCCMedia.BibleServer.GetVersesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetVerses, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::BCCMedia.BibleServer.GetVersesResponse> GetVersesAsync(global::BCCMedia.BibleServer.GetVersesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetVersesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::BCCMedia.BibleServer.GetVersesResponse> GetVersesAsync(global::BCCMedia.BibleServer.GetVersesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetVerses, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override BibleServerClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new BibleServerClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(BibleServerBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetVerses, serviceImpl.GetVerses).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, BibleServerBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetVerses, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::BCCMedia.BibleServer.GetVersesRequest, global::BCCMedia.BibleServer.GetVersesResponse>(serviceImpl.GetVerses));
    }

  }
}
#endregion
