// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: main.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace BCCMedia.BibleServer {

  /// <summary>Holder for reflection information generated from main.proto</summary>
  public static partial class MainReflection {

    #region Descriptor
    /// <summary>File descriptor for main.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MainReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgptYWluLnByb3RvEgtiaWJsZXNlcnZlciKZAQoFVmVyc2USCgoCaWQYASAB",
            "KAkSDAoEdGV4dBgCIAEoCRIOCgZudW1iZXIYAyABKA0SNAoJZm9vdG5vdGVz",
            "GAQgAygLMiEuYmlibGVzZXJ2ZXIuVmVyc2UuRm9vdG5vdGVzRW50cnkaMAoO",
            "Rm9vdG5vdGVzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4",
            "ASJsChBHZXRWZXJzZXNSZXF1ZXN0EhAKCGJpYmxlX2lkGAEgASgJEg8KB2Jv",
            "b2tfaWQYAiABKA0SDwoHY2hhcHRlchgDIAEoDRISCgp2ZXJzZV9mcm9tGAQg",
            "ASgNEhAKCHZlcnNlX3RvGAUgASgNIjcKEUdldFZlcnNlc1Jlc3BvbnNlEiIK",
            "BnZlcnNlcxgBIAMoCzISLmJpYmxlc2VydmVyLlZlcnNlMlkKC0JpYmxlU2Vy",
            "dmVyEkoKCUdldFZlcnNlcxIdLmJpYmxlc2VydmVyLkdldFZlcnNlc1JlcXVl",
            "c3QaHi5iaWJsZXNlcnZlci5HZXRWZXJzZXNSZXNwb25zZUI3Wh5nby5iY2Mu",
            "bWVkaWEvYmlibGVzZXJ2ZXIvcHJvdG+qAhRCQ0NNZWRpYS5CaWJsZVNlcnZl",
            "cmIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::BCCMedia.BibleServer.Verse), global::BCCMedia.BibleServer.Verse.Parser, new[]{ "Id", "Text", "Number", "Footnotes" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::BCCMedia.BibleServer.GetVersesRequest), global::BCCMedia.BibleServer.GetVersesRequest.Parser, new[]{ "BibleId", "BookId", "Chapter", "VerseFrom", "VerseTo" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::BCCMedia.BibleServer.GetVersesResponse), global::BCCMedia.BibleServer.GetVersesResponse.Parser, new[]{ "Verses" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Verse : pb::IMessage<Verse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Verse> _parser = new pb::MessageParser<Verse>(() => new Verse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Verse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BCCMedia.BibleServer.MainReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Verse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Verse(Verse other) : this() {
      id_ = other.id_;
      text_ = other.text_;
      number_ = other.number_;
      footnotes_ = other.footnotes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Verse Clone() {
      return new Verse(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private string id_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Id {
      get { return id_; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "text" field.</summary>
    public const int TextFieldNumber = 2;
    private string text_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Text {
      get { return text_; }
      set {
        text_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "number" field.</summary>
    public const int NumberFieldNumber = 3;
    private uint number_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Number {
      get { return number_; }
      set {
        number_ = value;
      }
    }

    /// <summary>Field number for the "footnotes" field.</summary>
    public const int FootnotesFieldNumber = 4;
    private static readonly pbc::MapField<string, string>.Codec _map_footnotes_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 34);
    private readonly pbc::MapField<string, string> footnotes_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::MapField<string, string> Footnotes {
      get { return footnotes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Verse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Verse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Text != other.Text) return false;
      if (Number != other.Number) return false;
      if (!Footnotes.Equals(other.Footnotes)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id.Length != 0) hash ^= Id.GetHashCode();
      if (Text.Length != 0) hash ^= Text.GetHashCode();
      if (Number != 0) hash ^= Number.GetHashCode();
      hash ^= Footnotes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Text.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Text);
      }
      if (Number != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Number);
      }
      footnotes_.WriteTo(output, _map_footnotes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Id);
      }
      if (Text.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Text);
      }
      if (Number != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Number);
      }
      footnotes_.WriteTo(ref output, _map_footnotes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (Text.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Text);
      }
      if (Number != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Number);
      }
      size += footnotes_.CalculateSize(_map_footnotes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Verse other) {
      if (other == null) {
        return;
      }
      if (other.Id.Length != 0) {
        Id = other.Id;
      }
      if (other.Text.Length != 0) {
        Text = other.Text;
      }
      if (other.Number != 0) {
        Number = other.Number;
      }
      footnotes_.Add(other.footnotes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Text = input.ReadString();
            break;
          }
          case 24: {
            Number = input.ReadUInt32();
            break;
          }
          case 34: {
            footnotes_.AddEntriesFrom(input, _map_footnotes_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Id = input.ReadString();
            break;
          }
          case 18: {
            Text = input.ReadString();
            break;
          }
          case 24: {
            Number = input.ReadUInt32();
            break;
          }
          case 34: {
            footnotes_.AddEntriesFrom(ref input, _map_footnotes_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetVersesRequest : pb::IMessage<GetVersesRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetVersesRequest> _parser = new pb::MessageParser<GetVersesRequest>(() => new GetVersesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetVersesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BCCMedia.BibleServer.MainReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetVersesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetVersesRequest(GetVersesRequest other) : this() {
      bibleId_ = other.bibleId_;
      bookId_ = other.bookId_;
      chapter_ = other.chapter_;
      verseFrom_ = other.verseFrom_;
      verseTo_ = other.verseTo_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetVersesRequest Clone() {
      return new GetVersesRequest(this);
    }

    /// <summary>Field number for the "bible_id" field.</summary>
    public const int BibleIdFieldNumber = 1;
    private string bibleId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BibleId {
      get { return bibleId_; }
      set {
        bibleId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "book_id" field.</summary>
    public const int BookIdFieldNumber = 2;
    private uint bookId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint BookId {
      get { return bookId_; }
      set {
        bookId_ = value;
      }
    }

    /// <summary>Field number for the "chapter" field.</summary>
    public const int ChapterFieldNumber = 3;
    private uint chapter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Chapter {
      get { return chapter_; }
      set {
        chapter_ = value;
      }
    }

    /// <summary>Field number for the "verse_from" field.</summary>
    public const int VerseFromFieldNumber = 4;
    private uint verseFrom_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint VerseFrom {
      get { return verseFrom_; }
      set {
        verseFrom_ = value;
      }
    }

    /// <summary>Field number for the "verse_to" field.</summary>
    public const int VerseToFieldNumber = 5;
    private uint verseTo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint VerseTo {
      get { return verseTo_; }
      set {
        verseTo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetVersesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetVersesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BibleId != other.BibleId) return false;
      if (BookId != other.BookId) return false;
      if (Chapter != other.Chapter) return false;
      if (VerseFrom != other.VerseFrom) return false;
      if (VerseTo != other.VerseTo) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (BibleId.Length != 0) hash ^= BibleId.GetHashCode();
      if (BookId != 0) hash ^= BookId.GetHashCode();
      if (Chapter != 0) hash ^= Chapter.GetHashCode();
      if (VerseFrom != 0) hash ^= VerseFrom.GetHashCode();
      if (VerseTo != 0) hash ^= VerseTo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BibleId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BibleId);
      }
      if (BookId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(BookId);
      }
      if (Chapter != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Chapter);
      }
      if (VerseFrom != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(VerseFrom);
      }
      if (VerseTo != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(VerseTo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BibleId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(BibleId);
      }
      if (BookId != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(BookId);
      }
      if (Chapter != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Chapter);
      }
      if (VerseFrom != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(VerseFrom);
      }
      if (VerseTo != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(VerseTo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (BibleId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BibleId);
      }
      if (BookId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BookId);
      }
      if (Chapter != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Chapter);
      }
      if (VerseFrom != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(VerseFrom);
      }
      if (VerseTo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(VerseTo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetVersesRequest other) {
      if (other == null) {
        return;
      }
      if (other.BibleId.Length != 0) {
        BibleId = other.BibleId;
      }
      if (other.BookId != 0) {
        BookId = other.BookId;
      }
      if (other.Chapter != 0) {
        Chapter = other.Chapter;
      }
      if (other.VerseFrom != 0) {
        VerseFrom = other.VerseFrom;
      }
      if (other.VerseTo != 0) {
        VerseTo = other.VerseTo;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BibleId = input.ReadString();
            break;
          }
          case 16: {
            BookId = input.ReadUInt32();
            break;
          }
          case 24: {
            Chapter = input.ReadUInt32();
            break;
          }
          case 32: {
            VerseFrom = input.ReadUInt32();
            break;
          }
          case 40: {
            VerseTo = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            BibleId = input.ReadString();
            break;
          }
          case 16: {
            BookId = input.ReadUInt32();
            break;
          }
          case 24: {
            Chapter = input.ReadUInt32();
            break;
          }
          case 32: {
            VerseFrom = input.ReadUInt32();
            break;
          }
          case 40: {
            VerseTo = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class GetVersesResponse : pb::IMessage<GetVersesResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GetVersesResponse> _parser = new pb::MessageParser<GetVersesResponse>(() => new GetVersesResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetVersesResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::BCCMedia.BibleServer.MainReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetVersesResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetVersesResponse(GetVersesResponse other) : this() {
      verses_ = other.verses_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetVersesResponse Clone() {
      return new GetVersesResponse(this);
    }

    /// <summary>Field number for the "verses" field.</summary>
    public const int VersesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::BCCMedia.BibleServer.Verse> _repeated_verses_codec
        = pb::FieldCodec.ForMessage(10, global::BCCMedia.BibleServer.Verse.Parser);
    private readonly pbc::RepeatedField<global::BCCMedia.BibleServer.Verse> verses_ = new pbc::RepeatedField<global::BCCMedia.BibleServer.Verse>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::BCCMedia.BibleServer.Verse> Verses {
      get { return verses_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetVersesResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetVersesResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!verses_.Equals(other.verses_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= verses_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      verses_.WriteTo(output, _repeated_verses_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      verses_.WriteTo(ref output, _repeated_verses_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += verses_.CalculateSize(_repeated_verses_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetVersesResponse other) {
      if (other == null) {
        return;
      }
      verses_.Add(other.verses_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            verses_.AddEntriesFrom(input, _repeated_verses_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            verses_.AddEntriesFrom(ref input, _repeated_verses_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
